### PR TITLE
Add github star button as template

### PR DESCRIPTION
**Pull request by droumis**
I have no idea what I'm doing. Let's see if this works

### CODE REVIEW

**Comment by maximlt** [comment]
Well that worked quite well :)

The only thing I'm unsure about is the look of it, the star of on the right looks a little misaligned. The whole badge doesn't look great to me but that's super subjective so forget about it, unless you feel the same.

image

**Comment by droumis** [comment]
It definitely has an outdated look, but since these syle of badges are everywhere I think people don't mind, and I'd rather be somewhat consistent with other badges used across our sites. I'm happy to remove the star. Is that enough you think?

**Comment by maximlt** [comment]
Feel free to merge the PR once you've made whatever change you choose to make!

**Comment by philippjfr** [comment]
Happy with this as a first cut, we can iterate on the badge styles later.

**Pull request merged**
